### ISSUE TITLE
trying to use a recycled bitmap fail on ICS

### ISSUE THREAD

**Issue by Vad1mo** [jasonpolites/gesture-imageview#33]
Hello Jason,

I am using gesture image view with an ics device and get  always a recycled bitmap error. On 2.1 devices there is no such error.

I created a condition to debug wehen I have a recycled bitmap but the if condition is never reached and isRecycled always returns false until I draw on the canvas
    @Override
    protected void onDraw(Canvas canvas) {
        if(layout) {
            if(drawable != null && !isRecycled()) {
                canvas.save();

```
            float adjustedScale = scale * scaleAdjust;

            canvas.translate(x, y);

            if(rotation != 0.0f) {
                canvas.rotate(rotation);
            }

            if(adjustedScale != 1.0f) {
                canvas.scale(adjustedScale, adjustedScale);
            }
```

// get here if recycled
                if ((drawable instanceof BitmapDrawable) && ((BitmapDrawable)drawable).getBitmap().isRecycled()){
                    log("recycled");  
                }else{
                    drawable.draw(canvas);
                }
                canvas.restore();
            }

```
        if(drawLock.availablePermits() <= 0) {
            drawLock.release();
        }
    }
}
```

07-02 13:18:11.497: E/AndroidRuntime(2022): java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@b48c3420
07-02 13:18:11.497: E/AndroidRuntime(2022):     at android.graphics.Canvas.throwIfRecycled(Canvas.java:1038)
07-02 13:18:11.497: E/AndroidRuntime(2022):     at android.graphics.Canvas.drawBitmap(Canvas.java:1142)
07-02 13:18:11.497: E/AndroidRuntime(2022):     at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:393)
07-02 13:18:11.497: E/AndroidRuntime(2022):     at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:345)
07-02 13:18:11.497: E/AndroidRuntime(2022):     at com.polites.android.GestureImageView.onDraw(GestureImageView.java:287)

du you have an idea what it might be? Is the error related to canvas or the bitmap

best regards,

**Comment by Vad1mo** [comment]
the error is not related to gesture image view. it was my failure in one of the layered drawables there was a recycled bitmap
